name: CppWarningNotifier
author: yaito3014
description: Notifies about C++ warnings in GitHub Actions

inputs:
  GITHUB_TOKEN:
    required: true
  PRIVATE_KEY:
    required: true
  JOB_REGEX:
    required: true
  STEP_REGEX:
    required: true
  ARTIFACT_REGEX:
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
