name: CppWarningNotifier
author: yaito3014
description: Notifies about C++ warnings in GitHub Actions

inputs:
  IGNORE_NO_MARKER:
    default: false
  RUN_ID:
    requird: true
  JOB_ID:
    required: true
  JOB_REGEX:
    required: true
  STEP_REGEX:
    required: true
  ROW_HEADERS:
    required: true
  COLUMN_HEADER:
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
