name: CppWarningNotifier
author: yaito3014
description: Notifies about C++ warnings in GitHub Actions

inputs:
  GITHUB_TOKEN:
    description: GitHub token for authentication
    required: true
  PRIVATE_KEY:
    description: Private key for GitHub App
    required: true
  JOB_REGEX:
    description: regex for job name parsing
    required: true
  STEP_REGEX:
    description: regex for step name filtering

runs:
  using: "node20"
  main: "dist/index.js"
