name: CppWarningNotifier
author: yaito3014
description: Notifies about C++ warnings in GitHub Actions

inputs:
  GITHUB_TOKEN:
    description: GitHub token for authentication
    required: true
  PRIVATE_KEY:
    description: Private key for GitHub App
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
